name: Build et Déploiement  

on:
  push:
    branches:
      - main
    paths:
      - '**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build et Déploiement
        working-directory: TP_Abir_KHARMACHI/TP
        run: |
          mvn clean install 
          docker build -f ../../Dockerfile -t abirkharmachi/imgspring:latest ../../ 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images to Docker Hub
        run: docker push abirkharmachi/imgspring:latest

      - name: Création du tag Git (v1.0.0)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag v1.0.0
          git push origin v1.0.0
          
